---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clustersentinel-data
  namespace: clustersentinel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
